"""empty message

Revision ID: cfe3cbfdc33e
Revises: 
Create Date: 2019-12-01 22:58:56.757647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cfe3cbfdc33e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('password', sa.String(length=100), nullable=False))
    op.drop_column('cms_user', '_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cms_user', sa.Column('_password', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('cms_user', 'password')
    # ### end Alembic commands ###
